### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by Matheus-Garbelini** [DannyBen/completely#28]
Hi, 

Does this project plans to a have a docker image ready to be used such as bashly?
Since Ubuntu 18.04 does not support ruby>2.7 via packager manager, I currently cannot use such project out-of-the box as compared to bashly.

Thanks.

**Comment by DannyBen** [comment]
I wasn't planning on it, since I did not think there was demand.
I will make one later today, no problem.

Will post here again when it is ready.

**Comment by DannyBen** [comment]
Done.

Updated the [installation instructions](https://github.com/DannyBen/completely#install) as well.

**Comment by Matheus-Garbelini** [comment]
@DannyBen Thanks a lot for your fast reply.

I'll try and let you know.

**Comment by DannyBen** [comment]
My pleasure. Thanks for taking the time to request it.

**Comment by baflo** [comment]
@DannyBen that's an awesome option for rapid prototyping. However, I cannot find the image, yet. Have you pushed it?

**Comment by Matheus-Garbelini** [comment]
@DannyBen indeed, i think that dannyben/completely is not public since I got the following after running the `completely` alias:
```bash
Unable to find image 'dannyben/completely:latest' locally
docker: Error response from daemon: pull access denied for dannyben/completely, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

```
