### ISSUE TITLE
Could we use another program completion ?

### ISSUE THREAD

**Issue by DimitriGilbert** [DannyBen/completely#55]
After a bit of searching, I found [that](https://stackoverflow.com/a/29247483) you could use `complete -F` to use another command completion and didn't find example of that in Completely.
Do you support it ? If not is it something you'd be considering ?
Thanks for your great work.

**Comment by DannyBen** [comment]
The `complete -F <function> <command>` command simply sets a bash function to serve as completions for a command.
It is used by all completion scripts, once.

You can see it at the end of the completely-generated completions script:

https://github.com/DannyBen/completely/blob/54dd2593dba9f8d9eeecaa4a81c18a0aca8b4210/lib/completely/templates/template.erb#L47

It cannot be "merged" with the other completions, if that is what you meant.

**Comment by DimitriGilbert** [comment]
There is no dumb question until there is, duh...Sorry about that.
But yeah that is what I meant. Freshened eyes and brains gave me the answer, "a bit like `sudo` but for a specific command", so I am going to look into that.
Thank you for the quick answer :)

**Comment by DannyBen** [comment]
Well - one thing that you *can* do and might help, is to blend completions from another external command.

If you run `completely init` you will get a sample file that contains a line with this syntax:
https://github.com/DannyBen/completely/blob/54dd2593dba9f8d9eeecaa4a81c18a0aca8b4210/lib/completely/templates/sample.yaml#L12

Any command that returns a whitespace delimited list, can be used.
Docs for this feature are [here](https://github.com/DannyBen/completely#suggesting-custom-dynamic-suggestions).

Also note that the completions are simply generated with the `compgen` - so if you find something in this command that is not implemented, and can be helpful - feel free to share.
