### ISSUE TITLE
Question: how to define completion rule for a `--option FILE` option?

### ISSUE THREAD

**Issue by postmodern** [DannyBen/completely#56]
Hello, how can I define a completion rule for an option which accepts a file. The examples show that one can define option flags under a command, and `<file>` keywords under a command, but can I do `--option <file>`?

Also you should enable GitHub Discussions so people can submit questions there, instead of cluttering up the Issues.

**Comment by DannyBen** [comment]
Isn't this what you are looking for?
[README > Suggesting flag arguments](https://github.com/DannyBen/completely?tab=readme-ov-file#suggesting-flag-arguments)

It would then be something like this:

```yaml
yourcli*--option:
- <file>
```

which you can test like this:

```
$ completely test "yourcli anything else --option "
```
