### ISSUE TITLE
Update the Zsh instructions on how to correctly use the Bash completions

### ISSUE THREAD

**Issue by postmodern** [DannyBen/completely#60]
After installing my completion files into `/usr/local/etc/bash_completion.d/` they are automatically loaded by Bash, but not by Zsh. Even after adding the suggested Zsh configuration to `~/.zshrc` the bash completions are not automatically loaded by Zsh. I think the Zsh instructions need to mention this, or that one must install the Bash completion files into `/usr/local/share/zsh/site-functions`. or that `~/.zshrc` should explicitly `source` the bash completions from wherever they were installed to.

**Comment by DannyBen** [comment]
👉 [README > Completions in ZSH](https://github.com/DannyBen/completely?tab=readme-ov-file#completions-in-zsh)

If there is a different, official set of instructions for ZSH, I am happy to update this section.

**Comment by postmodern** [comment]
After doing some testing, there are only two ways to get `zsh` to load bash completion files automatically on startup:

A. The compile files must start with a `_` in it's file name, and have both `#compdef command-name-here` followed by `#autoload` at the top of the completion files that are installed into `/usr/local/share/zsh/site-functions`. Note, any other shell script files installed into `/usr/local/share/zsh/site-functions` but without the `_` or those magic header comments will not be automatically loaded on startup, even if `bashcompinit` is called.
B. Explicitly `source` the completion files in `~/.zshrc` after the lines where you call `compinit` and `bashcompinit`.

As far as I can tell, stock `zsh` (version 5.9 on Fedora) will not automatically load the bash completion files, from any of the bash completion directories, even if `bashcompinit` is called.

Some zsh users on Mastodon seem to prefer option B, but I don't think the practice scales very well. I vote option A.

**Comment by DannyBen** [comment]
Well, personally I am not touching my `~/.bashrc` at all since I placed this code in it:

```bash
# Source all files in ~/.bashrc.d
for f in ~/.bashrc.d/*; do source $f; done
```

and from this point on, any update that requires something changed in `~/.bashrc`, I simply create a new file in `~/.bashrc.d`

I load completions in the same way, by having this `~/.bashrc.d/bash_completions.bashrc` file:

```bash
for bcfile in ~/.bash_completion.d/* ; do
  [ -f "$bcfile" ] && source $bcfile
done
```

But, as I said, completely is about generating the bash completions file, not installing, and definitely not solving every shell's peculiarities.

**Comment by postmodern** [comment]
All I am asking is for the missing details to be added to the Zsh instructions, for those wishing to install bash completions under Zsh. Something like:

```markdown
Note: bash completion files must be installed into `/usr/local/share/zsh/site-functions`, their file name must start with a `_` character, and the file must start with the `#compdef command-name-here` and `#autoload` magic comments in order for them to be autoloaded by `zsh`.
```

Would you accept a PR that adds that below the current Zsh configuration section?

**Comment by DannyBen** [comment]
> Would you accept a PR that adds that below the current Zsh configuration section?

I need a link to the formal zsh guide that states this, and that this is the recommended way to install completions.

**Comment by postmodern** [comment]
I found [this section](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#index-completion-system_002c-autoloaded-functions) in the Zsh Documentation that mentions `#compdef` and `#autoload`. Still trying to find a mention on why file names must start with a `_` character, or whether this is the recommended way of installing zsh completion files.

**Comment by DannyBen** [comment]
This is way too convoluted and sparse. zsh users have been autoloading bash completions without having `#compdef` comment... I am really not interested in becoming yet another source of misleading zsh completions installation.

The instructions I have placed in the README are complimentary, and are quoted as the solution in multiple places.

- https://stackoverflow.com/questions/3249432/can-a-bash-tab-completion-script-be-used-in-zsh
- https://docs.haskellstack.org/en/v1.6.5/shell_autocompletion/
- https://computingforgeeks.com/how-to-source-bash-completion-script-file-in-zsh/

At this point, I am either going to keep the zsh instructions as is, or remove them altogether.

**Comment by postmodern** [comment]
> This is way too convoluted and sparse. zsh users have been autoloading bash completions without having `#compdef` comment... I am really not interested in becoming yet another source of misleading zsh completions installation.
> 
> The instructions I have placed in the README are complimentary, and are quoted as the solution in multiple places.
> 
> * https://stackoverflow.com/questions/3249432/can-a-bash-tab-completion-script-be-used-in-zsh
> * https://docs.haskellstack.org/en/v1.6.5/shell_autocompletion/
> * https://computingforgeeks.com/how-to-source-bash-completion-script-file-in-zsh/
> 
> At this point, I am either going to keep the zsh instructions as is, or remove them altogether.

All of the examples you've linked to show explicitly `source`ing the completion files (`complete -C` is similar to `source`) or `eval`ing the completion shell script output, which if I'm not mistaken you were previously against doing?

To be fair, zsh is kind of convoluted. However, the documentation seems to confirm this is how it's supposed to work.

https://zsh.sourceforge.io/Doc/Release/Completion-System.html#index-completion-system_002c-autoloaded-functions
> The convention for autoloaded functions used in completion is that they start with an underscore; as already mentioned, the fpath/FPATH parameter must contain the directory in which they are stored. If zsh was properly installed on your system, then fpath/FPATH automatically contains the required directories for the standard functions.

> #compdef name ... [ -{p|P} pattern ... [ -N name ... ] ]
>
> > The file will be made autoloadable and the function defined in it will be called when completing names, each of which is either the name of a command whose arguments are to be completed or one of a number of special contexts in the form -context- described below.

> #autoload [ options ]
>
> > Functions with the #autoload tag are marked for autoloading but are not otherwise treated specially. Typically they are to be called from within one of the completion functions. Any options supplied will be passed to the autoload builtin; a typical use is +X to force the function to be loaded immediately. Note that the -U and -z flags are always added implicitly.

Feel free to test my instructions out yourself or inspect the existing zsh completions in `/usr/share/zsh/site-functions/`.

**Comment by postmodern** [comment]
Update: after further testing `#autoload` isn't necessary, as long as the filename starts with a `_` and the first line is `#compdef command-name-here`.

**Comment by DannyBen** [comment]
Sourcing the file means there is no use for autoloading, as it is already loaded.

In any case - the README instructions state how to enable bash completions in zsh. How you load it, is between you and your shell.

I am closing this issue, it is outside of completely's scope.
